-- Create Table for Hotel Profile
CREATE TABLE IF NOT EXISTS public.hotel_profile (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'PPKD Hotel',
    address TEXT,
    phone TEXT,
    email TEXT,
    logo_url TEXT,
    terms TEXT, -- Syarat & Ketentuan / Kebijakan Hotel
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert a default row if empty
INSERT INTO public.hotel_profile (name, address, phone, email)
SELECT 'PPKD Hotel', 'Jl. Contoh No. 123', '081234567890', 'hotel@ppkd.com'
WHERE NOT EXISTS (SELECT 1 FROM public.hotel_profile LIMIT 1);

-- Enable RLS
ALTER TABLE public.hotel_profile ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can View
DROP POLICY IF EXISTS "Allow anyone to view hotel profile" ON public.hotel_profile;
CREATE POLICY "Allow anyone to view hotel profile" 
ON public.hotel_profile FOR SELECT 
USING (true);

-- Policy: Only Superadmin and Admin can Update
DROP POLICY IF EXISTS "Allow Admin/Superadmin to update hotel profile" ON public.hotel_profile;
CREATE POLICY "Allow Admin/Superadmin to update hotel profile" 
ON public.hotel_profile FOR UPDATE 
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_roles.user_id = auth.uid() 
        AND user_roles.role IN ('Superadmin', 'Admin')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_roles.user_id = auth.uid() 
        AND user_roles.role IN ('Superadmin', 'Admin')
    )
);

-- Create Table for Shift Logs (Log Book Internal)
CREATE TABLE IF NOT EXISTS public.shift_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    username TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.shift_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can View
DROP POLICY IF EXISTS "Allow all authenticated to view shift logs" ON public.shift_logs;
CREATE POLICY "Allow all authenticated to view shift logs" 
ON public.shift_logs FOR SELECT 
TO authenticated 
USING (true);

-- Policy: Only logged in users can Insert their own message
DROP POLICY IF EXISTS "Allow users to insert shift logs" ON public.shift_logs;
CREATE POLICY "Allow users to insert shift logs" 
ON public.shift_logs FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Create Table for Room Rates (Manajemen Harga)
CREATE TABLE IF NOT EXISTS public.room_rates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type TEXT UNIQUE NOT NULL, -- 'Deluxe', 'Standard'
    base_price NUMERIC NOT NULL DEFAULT 0,
    seasonal_price NUMERIC, -- Harga musiman (optional)
    season_name TEXT, -- 'Peak Season', 'Promo'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert defaults for Deluxe, Standard & Suite
INSERT INTO public.room_rates (room_type, base_price)
VALUES 
('Deluxe', 2500000),
('Standard', 1500000),
('Suite', 4000000)
ON CONFLICT (room_type) DO NOTHING;

-- Enable RLS
ALTER TABLE public.room_rates ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can View
DROP POLICY IF EXISTS "Allow anyone to view room rates" ON public.room_rates;
CREATE POLICY "Allow anyone to view room rates" 
ON public.room_rates FOR SELECT 
USING (true);

-- Policy: Only Admin/Superadmin can Update
DROP POLICY IF EXISTS "Allow Admin/Superadmin to update room rates" ON public.room_rates;
CREATE POLICY "Allow Admin/Superadmin to update room rates" 
ON public.room_rates FOR UPDATE 
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_roles.user_id = auth.uid() 
        AND user_roles.role IN ('Superadmin', 'Admin')
    )
);


